# Read-only — Phase 2 consumer populates user_id at startup via batch API lookup
REPORTERS = [
    {"handle": "JakeDRill",       "user_id": None, "team": "Orioles"},
    {"handle": "masnRoch",        "user_id": None, "team": "Orioles"},
    {"handle": "IanMBrowne",      "user_id": None, "team": "Red Sox"},
    {"handle": "alexspeier",      "user_id": None, "team": "Red Sox"},
    {"handle": "BryanHoch",       "user_id": None, "team": "Yankees"},
    {"handle": "GJoyce9",         "user_id": None, "team": "Yankees"},
    {"handle": "adamdberry",      "user_id": None, "team": "Rays"},
    {"handle": "TBTimes_Rays",    "user_id": None, "team": "Rays"},
    {"handle": "KeeganMatheson",  "user_id": None, "team": "Blue Jays"},
    {"handle": "ShiDavidi",       "user_id": None, "team": "Blue Jays"},
    {"handle": "scottmerkin",     "user_id": None, "team": "White Sox"},
    {"handle": "JRFegan",         "user_id": None, "team": "White Sox"},
    {"handle": "ZackMeisel",      "user_id": None, "team": "Guardians"},
    {"handle": "beckjason",       "user_id": None, "team": "Tigers"},
    {"handle": "CodyStavenhagen", "user_id": None, "team": "Tigers"},
    {"handle": "alec_lewis",      "user_id": None, "team": "Royals"},
    {"handle": "DanHayesMLB",     "user_id": None, "team": "Twins"},
    {"handle": "dohyoungpark",    "user_id": None, "team": "Twins"},
    {"handle": "brianmctaggart",  "user_id": None, "team": "Astros"},
    {"handle": "Chandler_Rome",   "user_id": None, "team": "Astros"},
    {"handle": "RhettBollinger",  "user_id": None, "team": "Angels"},
    {"handle": "JeffFletcherOCR", "user_id": None, "team": "Angels"},
    {"handle": "MartinJGallegos", "user_id": None, "team": "Athletics"},
    {"handle": "DKramer_",        "user_id": None, "team": "Mariners"},
    {"handle": "RyanDivish",      "user_id": None, "team": "Mariners"},
    {"handle": "kennlandry",      "user_id": None, "team": "Rangers"},
    {"handle": "Evan_P_Grant",    "user_id": None, "team": "Rangers"},
    {"handle": "mlbbowman",       "user_id": None, "team": "Braves"},
    {"handle": "DOBrienATL",      "user_id": None, "team": "Braves"},
    {"handle": "AnthonyDiComo",   "user_id": None, "team": "Mets"},
    {"handle": "TimBritton",      "user_id": None, "team": "Mets"},
    {"handle": "ToddZolecki",     "user_id": None, "team": "Phillies"},
    {"handle": "MattGelb",        "user_id": None, "team": "Phillies"},
    {"handle": "CDeNicola13",     "user_id": None, "team": "Marlins"},
    {"handle": "J_McPherson1126", "user_id": None, "team": "Marlins"},
    {"handle": "JessicaCamerato", "user_id": None, "team": "Nationals"},
    {"handle": "MarkZuckerman",   "user_id": None, "team": "Nationals"},
    {"handle": "MLBastian",       "user_id": None, "team": "Cubs"},
    {"handle": "sahadevsharma",   "user_id": None, "team": "Cubs"},
    {"handle": "m_sheldon",       "user_id": None, "team": "Reds"},
    {"handle": "AdamMcCalvy",     "user_id": None, "team": "Brewers"},
    {"handle": "Todd_Rosiak",     "user_id": None, "team": "Brewers"},
    {"handle": "justdelossantos", "user_id": None, "team": "Pirates"},
    {"handle": "katiejwoo",       "user_id": None, "team": "Cardinals"},
    {"handle": "JohnDenton555",   "user_id": None, "team": "Cardinals"},
    {"handle": "SteveGilbertMLB", "user_id": None, "team": "Diamondbacks"},
    {"handle": "nickpiecoro",     "user_id": None, "team": "Diamondbacks"},
    {"handle": "harding_at_mlb",  "user_id": None, "team": "Rockies"},
    {"handle": "psaundersdp",     "user_id": None, "team": "Rockies"},
    {"handle": "juanctoribio",    "user_id": None, "team": "Dodgers"},
    {"handle": "billplunkettocr", "user_id": None, "team": "Dodgers"},
    {"handle": "AJCassavell",     "user_id": None, "team": "Padres"},
    {"handle": "dennistlin",      "user_id": None, "team": "Padres"},
    {"handle": "extrabaggs",      "user_id": None, "team": "Giants"},
    {"handle": "mi_guardado",     "user_id": None, "team": "Giants"},
]
